### ISSUE TITLE
Null Safety ?

### ISSUE THREAD

**Issue by pr-1** [natintosh/intl_phone_number_input#182]
When are you planning to migrate the repo to null safety ?

**Comment by natintosh** [comment]
Yes

**Comment by cedvdb** [comment]
> When are you planning to migrate the repo to null safety ?

You might want to submit a PR ?

**Comment by pr-1** [comment]
I have submitted a pr on libphonenumber for now. Unless they merge it we cannot update as it is in the dependency. So waiting for them to review it. Or maybe i can use the package from my github link ? If that is okay then I am happy to work on this.

**Comment by luckyhandler** [comment]
@pr-1 you could reference your pr in the pubspec for now for a prerelease, e.g. like I did with this one:
```
  feature_discovery:
    git:
      url: https://github.com/ayalma/feature_discovery.git
      ref: 6c2ab0928f88082d0ac723fbc3e84adfbda6d587
```
