### ISSUE TITLE
intl_phone_number_input from git doesn't exist

### ISSUE THREAD

**Issue by pieterbergmans** [natintosh/intl_phone_number_input#458]
Hi, I tried getting the latest version 0.8.0 of this package from github using:
```
  intl_phone_number_input:
    git:    
      url: https://github.com/natintosh/intl_phone_number_input.git
      ref: 0.8.0
```
But I get the following error: _Because my_project depends on intl_phone_number_input from git which doesn't exist (Could not find git ref  '0.8.0' (fatal: ambiguous argument '0.8.0': unknown revision or path not in the working tree._

Any ideas on how to fix this?
